[build]
  command = "npm install && npm run build"   # You can modify if you have a build step
  publish = "public"                         # The folder where static assets are located
  functions = "functions"                    # The folder for serverless functions

[[redirects]]
  from = "/api/*"                            # Redirect to serverless functions
  to = "/.netlify/functions/:splat"          # Route to the correct function
  status = 200
