[build]
  command = "npm install && npm run build"   # Use npm build if you need one
  publish = "/"                               # Publish the root directory
  functions = "functions"                     # Point to your functions folder

[[redirects]]
  from = "/api/*"                            # Redirect to serverless functions
  to = "/.netlify/functions/:splat"          # Route to the correct function
  status = 200
